import type { EnemyCategory } from "@/game/domain/types";

export type EnemyDefinition = {
  id: string;
  name: string;
  category: EnemyCategory;
  health: number;
  speed: number;
  damage: number;
  xpReward: number;
};

export const ENEMIES = [
  {
    id: "data-colossus",
    name: "Data Colossus",
    category: "Challenge",
    health: 40,
    speed: 52,
    damage: 12,
    xpReward: 12,
  },
  {
    id: "null-wraith",
    name: "Null Wraith",
    category: "Bug",
    health: 35,
    speed: 90,
    damage: 8,
    xpReward: 25,
  },
  {
    id: "null-wraith-miniboss",
    name: "Null Wraith",
    category: "Bug",
    health: 175,
    speed: 90,
    damage: 24,
    xpReward: 125,
  },
  {
    id: "syntax-gremlin",
    name: "Syntax Gremlin",
    category: "Bug",
    health: 25,
    speed: 110,
    damage: 5,
    xpReward: 15,
  },
  {
    id: "merge-conflict-mimic",
    name: "Merge Conflict Mimic",
    category: "Bug",
    health: 55,
    speed: 70,
    damage: 10,
    xpReward: 45,
  },
  {
    id: "memory-leech",
    name: "Memory Leech",
    category: "Bug",
    health: 70,
    speed: 60,
    damage: 14,
    xpReward: 60,
  },
  {
    id: "race-condition-raider",
    name: "Race Condition Raider",
    category: "Bug",
    health: 60,
    speed: 120,
    damage: 15,
    xpReward: 70,
  },
  {
    id: "infinite-loop-serpent",
    name: "Infinite Loop Serpent",
    category: "Bug",
    health: 100,
    speed: 40,
    damage: 16,
    xpReward: 85,
  },
  {
    id: "stack-overflow-ogre",
    name: "Stack Overflow Ogre",
    category: "Challenge",
    health: 140,
    speed: 35,
    damage: 20,
    xpReward: 140,
  },
  {
    id: "dependency-hydra",
    name: "Dependency Hydra",
    category: "Challenge",
    health: 160,
    speed: 45,
    damage: 18,
    xpReward: 175,
  },
  {
    id: "technical-debt-golem",
    name: "Technical Debt Golem",
    category: "Challenge",
    health: 220,
    speed: 20,
    damage: 24,
    xpReward: 225,
  },
  {
    id: "legacy-specter",
    name: "Legacy Specter",
    category: "Challenge",
    health: 180,
    speed: 38,
    damage: 19,
    xpReward: 180,
  },
  {
    id: "spaghetti-horror",
    name: "Spaghetti Horror",
    category: "Challenge",
    health: 200,
    speed: 55,
    damage: 22,
    xpReward: 210,
  },
  {
    id: "off-by-one-imp",
    name: "Off-by-One Imp",
    category: "Bug",
    health: 20,
    speed: 130,
    damage: 4,
    xpReward: 10,
  },
  {
    id: "callback-banshee",
    name: "Callback Banshee",
    category: "Bug",
    health: 45,
    speed: 80,
    damage: 11,
    xpReward: 40,
  },
  {
    id: "broken-build-knight",
    name: "Broken Build Knight",
    category: "Challenge",
    health: 110,
    speed: 50,
    damage: 15,
    xpReward: 115,
  },
  {
    id: "timeout-beast",
    name: "Timeout Beast",
    category: "Challenge",
    health: 90,
    speed: 65,
    damage: 17,
    xpReward: 95,
  },
  {
    id: "deadlock-titan",
    name: "Deadlock Titan",
    category: "Boss",
    health: 300,
    speed: 15,
    damage: 30,
    xpReward: 400,
  },
  {
    id: "production-dragon",
    name: "Production Dragon",
    category: "Boss",
    health: 450,
    speed: 40,
    damage: 35,
    xpReward: 600,
  },
  {
    id: "bug-king",
    name: "Bug King",
    category: "Boss",
    health: 500,
    speed: 45,
    damage: 40,
    xpReward: 750,
  },
  {
    id: "spacing-wisp",
    name: "Spacing Wisp",
    category: "Bug",
    health: 30,
    speed: 85,
    damage: 6,
    xpReward: 10,
  },
] as const satisfies readonly EnemyDefinition[];
