import type { GitFetchUpgradeDefinition } from "@/game/domain/sprint";

export const GIT_FETCH_UPGRADES = [
  {
    id: "javascript-damage-green",
    label: "JS Damage Patch",
    description: "+10 flat damage for Event Spark Wand.",
    cost: 21,
    rarity: "common",
    kind: "weapon-upgrade",
    weaponSlot: "language",
    maxPurchases: 1,
    effect: { field: "damage", amount: 10 },
  },
  {
    id: "javascript-damage-blue",
    label: "JS Refactor Strike",
    description: "+20 flat damage for Event Spark Wand.",
    cost: 42,
    rarity: "uncommon",
    kind: "weapon-upgrade",
    weaponSlot: "language",
    maxPurchases: 1,
    effect: { field: "damage", amount: 20 },
  },
  {
    id: "javascript-damage-gold",
    label: "JS Critical Patch",
    description: "+40 flat damage for Event Spark Wand.",
    cost: 78,
    rarity: "rare",
    kind: "weapon-upgrade",
    weaponSlot: "language",
    maxPurchases: 1,
    effect: { field: "damage", amount: 40 },
  },
  {
    id: "javascript-cooldown-green",
    label: "Hot Reload",
    description: "Reduce Event Spark Wand cooldown by 8%.",
    cost: 21,
    rarity: "common",
    kind: "weapon-upgrade",
    weaponSlot: "language",
    maxPurchases: 1,
    effect: { field: "cooldown", multiplier: 0.92 },
  },
  {
    id: "javascript-cooldown-blue",
    label: "Fast Refresh",
    description: "Reduce Event Spark Wand cooldown by 16%.",
    cost: 45,
    rarity: "uncommon",
    kind: "weapon-upgrade",
    weaponSlot: "language",
    maxPurchases: 1,
    effect: { field: "cooldown", multiplier: 0.84 },
  },
  {
    id: "javascript-cooldown-gold",
    label: "Zero Downtime",
    description: "Reduce Event Spark Wand cooldown by 28%.",
    cost: 84,
    rarity: "rare",
    kind: "weapon-upgrade",
    weaponSlot: "language",
    maxPurchases: 1,
    effect: { field: "cooldown", multiplier: 0.72 },
  },
  {
    id: "javascript-projectile-gold",
    label: "Parallel Emit",
    description: "+1 Event Spark Wand beam from the player.",
    cost: 72,
    rarity: "rare",
    kind: "weapon-upgrade",
    weaponSlot: "language",
    maxPurchases: 3,
    effect: { field: "projectileCount", amount: 1 },
  },
  {
    id: "javascript-bounce-gold",
    label: "Async Bounce",
    description: "+1 jump from the struck enemy to a nearby target.",
    cost: 66,
    rarity: "rare",
    kind: "weapon-upgrade",
    weaponSlot: "language",
    maxPurchases: 3,
    effect: { field: "bounceCount", amount: 1 },
  },
  {
    id: "sql-damage-green",
    label: "Indexed Damage",
    description: "+5 flat damage for Querystring Bow.",
    cost: 18,
    rarity: "common",
    kind: "weapon-upgrade",
    weaponSlot: "sql",
    maxPurchases: 1,
    effect: { field: "damage", amount: 5 },
  },
  {
    id: "sql-damage-blue",
    label: "Optimized Query",
    description: "+10 flat damage for Querystring Bow.",
    cost: 36,
    rarity: "uncommon",
    kind: "weapon-upgrade",
    weaponSlot: "sql",
    maxPurchases: 1,
    effect: { field: "damage", amount: 10 },
  },
  {
    id: "sql-damage-gold",
    label: "Materialized Hit",
    description: "+20 flat damage for Querystring Bow.",
    cost: 69,
    rarity: "rare",
    kind: "weapon-upgrade",
    weaponSlot: "sql",
    maxPurchases: 1,
    effect: { field: "damage", amount: 20 },
  },
  {
    id: "sql-cooldown-green",
    label: "Prepared Statement",
    description: "Reduce Querystring Bow cooldown by 8%.",
    cost: 21,
    rarity: "common",
    kind: "weapon-upgrade",
    weaponSlot: "sql",
    maxPurchases: 1,
    effect: { field: "cooldown", multiplier: 0.92 },
  },
  {
    id: "sql-cooldown-blue",
    label: "Cached Query",
    description: "Reduce Querystring Bow cooldown by 16%.",
    cost: 45,
    rarity: "uncommon",
    kind: "weapon-upgrade",
    weaponSlot: "sql",
    maxPurchases: 1,
    effect: { field: "cooldown", multiplier: 0.84 },
  },
  {
    id: "sql-cooldown-gold",
    label: "Query Planner",
    description: "Reduce Querystring Bow cooldown by 28%.",
    cost: 84,
    rarity: "rare",
    kind: "weapon-upgrade",
    weaponSlot: "sql",
    maxPurchases: 1,
    effect: { field: "cooldown", multiplier: 0.72 },
  },
  {
    id: "sql-projectile-gold",
    label: "SELECT Many",
    description: "+1 Querystring Bow projectile.",
    cost: 69,
    rarity: "rare",
    kind: "weapon-upgrade",
    weaponSlot: "sql",
    maxPurchases: 3,
    effect: { field: "projectileCount", amount: 1 },
  },
  {
    id: "sql-pierce-gold",
    label: "JOIN Pierce",
    description: "+1 pierce for Querystring Bow.",
    cost: 57,
    rarity: "rare",
    kind: "weapon-upgrade",
    weaponSlot: "sql",
    maxPurchases: 4,
    effect: { field: "pierce", amount: 1 },
  },
] as const satisfies readonly GitFetchUpgradeDefinition[];

export type GitFetchUpgradeId = (typeof GIT_FETCH_UPGRADES)[number]["id"];
